Controllers/DepartmentsController.cs
using System.Diagnostics;
using VendasWebMvc.Models.ViewModels;
namespace VendasWebMvc.Controllers;

public class DepartmentsController : Controller
{
    private readonly ApplicationDbContext _context;
    private readonly DepartmentService _departmentService;

    public DepartmentsController(ApplicationDbContext context, DepartmentService departmentService)
    {
        _context = context;
        _departmentService = departmentService;
    }

    public async Task<IActionResult> Index()
    {
        var result = await _departmentService.FindAll();
        return View(result);
    }
    public IActionResult Create()
    {
        return View();
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(Department dept)
    {
        await _departmentService.Inserir(dept);
        return RedirectToAction(nameof(Index));

    }
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
            return RedirectToAction(nameof(Error), new { message = "Id não fornecido" });

        var result = await _departmentService.FindById(id.Value);
        if (result == null)
            return RedirectToAction(nameof(Error), new { message = "Id não encontrado" });

        return View(result);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int id)
    {
        await _departmentService.Remove(id);
        return RedirectToAction(nameof(Index));
    }
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
            return RedirectToAction(nameof(Error), new { message = "Id não informado" });

        var result = await _departmentService.FindById(id.Value);
        if (result == null)
            return RedirectToAction(nameof(Error), new { message = "Id não encontrado" });

        return View(result);
    }
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
            return RedirectToAction(nameof(Error), new { message = "Id não informado" });

        var result = await _departmentService.FindById(id.Value);
        if (result == null)
            return RedirectToAction(nameof(Error), new { message = "Id não encontrado" });

        return View(result);
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, Department dept)
    {
        if (id != dept.Id)
            return RedirectToAction(nameof(Error), new { message = "Id divergente" });
        try
        {
            await _departmentService.Update(dept);
            return RedirectToAction(nameof(Index));
        }
        catch (ApplicationException e)
        {

            return RedirectToAction(nameof(Error), new { message = e.Message });
        }
    }
    public IActionResult Error(string message)
    {
        var viewModel = new ErrorViewModel
        {
            Message = message,
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier
        };
        return View(viewModel);
    }
}

Controllers/SalesRecordsController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace VendasWebMvc.Controllers;

public class SalesRecordsController : Controller
{
    private readonly SalesRecordService _salesRecordService;

    public SalesRecordsController(SalesRecordService salesRecordService)
    {
        _salesRecordService = salesRecordService;
    }

    public IActionResult Index()
    {
        return View();
    }
    public async Task<IActionResult> SimpleSearch(DateTime? minDate, DateTime? maxDate)
    {
        if (!minDate.HasValue)
        {
            minDate = new DateTime(DateTime.Now.Year, 1, 1);
        }
        if (!maxDate.HasValue)
        {
            maxDate = DateTime.Now;
        }
        ViewData["minDate"] = minDate.Value.ToString("dd/MM/yyyy");
        ViewData["maxDate"] = maxDate.Value.ToString("dd/MM/yyyy");
        var result = await _salesRecordService.FindByDate(minDate, maxDate);
        return View(result);
    }
    public async Task<IActionResult> GroupingSearch(DateTime? minDate, DateTime? maxDate)
        {
            if (!minDate.HasValue)
            {
                minDate = new DateTime(DateTime.Now.Year, 1, 1);
            }
            if (!maxDate.HasValue)
            {
                maxDate = DateTime.Now;
            }
            ViewData["minDate"] = minDate.Value.ToString("yyyy-MM-dd");
            ViewData["maxDate"] = maxDate.Value.ToString("yyyy-MM-dd");
            var result = await _salesRecordService.FindByDateGrouping(minDate, maxDate);
            return View(result);
        }
}

Controllers/SellersController.cs
using System.Diagnostics;
using VendasWebMvc.Models.ViewModels;

namespace VendasWebMvc.Controllers;

public class SellersController : Controller
{
    private readonly SellerService _sellerService;
    private readonly DepartmentService _departmentService;

    public SellersController(SellerService sellerService, DepartmentService departmentService)
    {
        _sellerService = sellerService;
        _departmentService = departmentService;
    }

    public async Task<IActionResult> Index()
    {
        var list = await _sellerService.FindAll();
        return View(list);
    }
    public async Task<IActionResult> Create()
    {
        var department = await _departmentService.FindAll();
        var viewModel = new SellerViewModel { Departments = department };
        return View(viewModel);
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(Seller seller)
    {
        if (!ModelState.IsValid)//Caso o javascript não funcione
        {
            var department = await _departmentService.FindAll();
            var viewModel = new SellerViewModel { Seller = seller, Departments = department };
            return View(viewModel);
        }

        await _sellerService.Insert(seller);
        return RedirectToAction(nameof(Index));
    }
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
            return RedirectToAction(nameof(Error), new { message = "Id não fornecido" });

        var result = await _sellerService.FindById(id.Value);
        if (result == null)
            return RedirectToAction(nameof(Error), new { message = "Id não encontrado" });
        return View(result);
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int id)
    {
        await _sellerService.Delete(id);
        return RedirectToAction(nameof(Index));
    }
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
            return RedirectToAction(nameof(Error), new { message = "Id não informado" });
        var result = await _sellerService.FindById(id.Value);
        return View(result);
    }
    public async Task<IActionResult> Edit(int? id)
    {
        var result = await _sellerService.FindById(id.Value);
        if (result == null)
            return RedirectToAction(nameof(Error), new { message = "Id não encontrado" });

        List<Department> department = await _departmentService.FindAll();
        var viewModel = new SellerViewModel { Seller = result, Departments = department };
        return View(viewModel);
    }
    [HttpPost]
    public async Task<IActionResult> Edit(int id, Seller seller)
    {
        if (ModelState.IsValid)//Caso o javascript não funcione
        {
            var department = await _departmentService.FindAll();
            var viewModel = new SellerViewModel { Seller = seller, Departments = department };
            return View(viewModel);
        }

        if (id != seller.Id)
            return RedirectToAction(nameof(Error), new { message = "Id divergente" });

        try
        {
            await _sellerService.Update(seller);
            return RedirectToAction(nameof(Index));
        }
        catch (ApplicationException e)
        {

            return RedirectToAction(nameof(Error), new { message = e.Message });
        }
    }
    public IActionResult Error(string message)
    {
        var viewModel = new ErrorViewModel
        {
            Message = message,
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier
        };
        return View(viewModel);
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VendasWebMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-spacelab.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VendasWebMvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VendasWebMvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Departments" asp-action="Index">Departamento</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Sellers" asp-action="Index">Vendedores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="SalesRecords" asp-action="Index">Vendas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-white bg-dark">
        <div class="container">
            &copy; 2023 - VendasWebMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy text-white">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>